// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_chat_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_chat_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "user.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_chat_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_chat_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_chat_2eproto;
namespace protocol {
namespace chat {
class ChatHistoryRequest;
struct ChatHistoryRequestDefaultTypeInternal;
extern ChatHistoryRequestDefaultTypeInternal _ChatHistoryRequest_default_instance_;
class ChatHistoryResponse;
struct ChatHistoryResponseDefaultTypeInternal;
extern ChatHistoryResponseDefaultTypeInternal _ChatHistoryResponse_default_instance_;
class ChatMessage;
struct ChatMessageDefaultTypeInternal;
extern ChatMessageDefaultTypeInternal _ChatMessage_default_instance_;
class ChatNotify;
struct ChatNotifyDefaultTypeInternal;
extern ChatNotifyDefaultTypeInternal _ChatNotify_default_instance_;
class ChatPacket;
struct ChatPacketDefaultTypeInternal;
extern ChatPacketDefaultTypeInternal _ChatPacket_default_instance_;
class ChatReadAck;
struct ChatReadAckDefaultTypeInternal;
extern ChatReadAckDefaultTypeInternal _ChatReadAck_default_instance_;
class ChatSendRequest;
struct ChatSendRequestDefaultTypeInternal;
extern ChatSendRequestDefaultTypeInternal _ChatSendRequest_default_instance_;
class ChatSendResponse;
struct ChatSendResponseDefaultTypeInternal;
extern ChatSendResponseDefaultTypeInternal _ChatSendResponse_default_instance_;
}  // namespace chat
}  // namespace protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::protocol::chat::ChatHistoryRequest* Arena::CreateMaybeMessage<::protocol::chat::ChatHistoryRequest>(Arena*);
template<> ::protocol::chat::ChatHistoryResponse* Arena::CreateMaybeMessage<::protocol::chat::ChatHistoryResponse>(Arena*);
template<> ::protocol::chat::ChatMessage* Arena::CreateMaybeMessage<::protocol::chat::ChatMessage>(Arena*);
template<> ::protocol::chat::ChatNotify* Arena::CreateMaybeMessage<::protocol::chat::ChatNotify>(Arena*);
template<> ::protocol::chat::ChatPacket* Arena::CreateMaybeMessage<::protocol::chat::ChatPacket>(Arena*);
template<> ::protocol::chat::ChatReadAck* Arena::CreateMaybeMessage<::protocol::chat::ChatReadAck>(Arena*);
template<> ::protocol::chat::ChatSendRequest* Arena::CreateMaybeMessage<::protocol::chat::ChatSendRequest>(Arena*);
template<> ::protocol::chat::ChatSendResponse* Arena::CreateMaybeMessage<::protocol::chat::ChatSendResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protocol {
namespace chat {

enum TargetType : int {
  TARGET_TYPE_UNSPECIFIED = 0,
  TARGET_TYPE_USER = 1,
  TARGET_TYPE_GROUP = 2,
  TargetType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  TargetType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool TargetType_IsValid(int value);
constexpr TargetType TargetType_MIN = TARGET_TYPE_UNSPECIFIED;
constexpr TargetType TargetType_MAX = TARGET_TYPE_GROUP;
constexpr int TargetType_ARRAYSIZE = TargetType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TargetType_descriptor();
template<typename T>
inline const std::string& TargetType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TargetType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TargetType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TargetType_descriptor(), enum_t_value);
}
inline bool TargetType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, TargetType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TargetType>(
    TargetType_descriptor(), name, value);
}
enum MsgType : int {
  MSG_TYPE_TEXT = 0,
  MSG_TYPE_IMAGE = 1,
  MSG_TYPE_FILE = 2,
  MsgType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MsgType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MsgType_IsValid(int value);
constexpr MsgType MsgType_MIN = MSG_TYPE_TEXT;
constexpr MsgType MsgType_MAX = MSG_TYPE_FILE;
constexpr int MsgType_ARRAYSIZE = MsgType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MsgType_descriptor();
template<typename T>
inline const std::string& MsgType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MsgType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MsgType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MsgType_descriptor(), enum_t_value);
}
inline bool MsgType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MsgType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MsgType>(
    MsgType_descriptor(), name, value);
}
// ===================================================================

class ChatMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.chat.ChatMessage) */ {
 public:
  inline ChatMessage() : ChatMessage(nullptr) {}
  ~ChatMessage() override;
  explicit PROTOBUF_CONSTEXPR ChatMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChatMessage(const ChatMessage& from);
  ChatMessage(ChatMessage&& from) noexcept
    : ChatMessage() {
    *this = ::std::move(from);
  }

  inline ChatMessage& operator=(const ChatMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatMessage& operator=(ChatMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChatMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChatMessage* internal_default_instance() {
    return reinterpret_cast<const ChatMessage*>(
               &_ChatMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ChatMessage& a, ChatMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ChatMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChatMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChatMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChatMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChatMessage& from) {
    ChatMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChatMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.chat.ChatMessage";
  }
  protected:
  explicit ChatMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 5,
    kMsgIdFieldNumber = 1,
    kFromIdFieldNumber = 2,
    kToIdFieldNumber = 3,
    kTsFieldNumber = 6,
    kToTypeFieldNumber = 4,
  };
  // string content = 5;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // uint64 msg_id = 1;
  void clear_msg_id();
  uint64_t msg_id() const;
  void set_msg_id(uint64_t value);
  private:
  uint64_t _internal_msg_id() const;
  void _internal_set_msg_id(uint64_t value);
  public:

  // uint32 from_id = 2;
  void clear_from_id();
  uint32_t from_id() const;
  void set_from_id(uint32_t value);
  private:
  uint32_t _internal_from_id() const;
  void _internal_set_from_id(uint32_t value);
  public:

  // uint32 to_id = 3;
  void clear_to_id();
  uint32_t to_id() const;
  void set_to_id(uint32_t value);
  private:
  uint32_t _internal_to_id() const;
  void _internal_set_to_id(uint32_t value);
  public:

  // uint64 ts = 6;
  void clear_ts();
  uint64_t ts() const;
  void set_ts(uint64_t value);
  private:
  uint64_t _internal_ts() const;
  void _internal_set_ts(uint64_t value);
  public:

  // .protocol.chat.TargetType to_type = 4;
  void clear_to_type();
  ::protocol::chat::TargetType to_type() const;
  void set_to_type(::protocol::chat::TargetType value);
  private:
  ::protocol::chat::TargetType _internal_to_type() const;
  void _internal_set_to_type(::protocol::chat::TargetType value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.chat.ChatMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
    uint64_t msg_id_;
    uint32_t from_id_;
    uint32_t to_id_;
    uint64_t ts_;
    int to_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class ChatSendRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.chat.ChatSendRequest) */ {
 public:
  inline ChatSendRequest() : ChatSendRequest(nullptr) {}
  ~ChatSendRequest() override;
  explicit PROTOBUF_CONSTEXPR ChatSendRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChatSendRequest(const ChatSendRequest& from);
  ChatSendRequest(ChatSendRequest&& from) noexcept
    : ChatSendRequest() {
    *this = ::std::move(from);
  }

  inline ChatSendRequest& operator=(const ChatSendRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatSendRequest& operator=(ChatSendRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChatSendRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChatSendRequest* internal_default_instance() {
    return reinterpret_cast<const ChatSendRequest*>(
               &_ChatSendRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ChatSendRequest& a, ChatSendRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ChatSendRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatSendRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChatSendRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChatSendRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChatSendRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChatSendRequest& from) {
    ChatSendRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChatSendRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.chat.ChatSendRequest";
  }
  protected:
  explicit ChatSendRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 2,
    kClientTsFieldNumber = 3,
    kToIdFieldNumber = 1,
  };
  // string content = 2;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // uint64 client_ts = 3;
  void clear_client_ts();
  uint64_t client_ts() const;
  void set_client_ts(uint64_t value);
  private:
  uint64_t _internal_client_ts() const;
  void _internal_set_client_ts(uint64_t value);
  public:

  // uint32 to_id = 1;
  void clear_to_id();
  uint32_t to_id() const;
  void set_to_id(uint32_t value);
  private:
  uint32_t _internal_to_id() const;
  void _internal_set_to_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.chat.ChatSendRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
    uint64_t client_ts_;
    uint32_t to_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class ChatSendResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.chat.ChatSendResponse) */ {
 public:
  inline ChatSendResponse() : ChatSendResponse(nullptr) {}
  ~ChatSendResponse() override;
  explicit PROTOBUF_CONSTEXPR ChatSendResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChatSendResponse(const ChatSendResponse& from);
  ChatSendResponse(ChatSendResponse&& from) noexcept
    : ChatSendResponse() {
    *this = ::std::move(from);
  }

  inline ChatSendResponse& operator=(const ChatSendResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatSendResponse& operator=(ChatSendResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChatSendResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChatSendResponse* internal_default_instance() {
    return reinterpret_cast<const ChatSendResponse*>(
               &_ChatSendResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ChatSendResponse& a, ChatSendResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ChatSendResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatSendResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChatSendResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChatSendResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChatSendResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChatSendResponse& from) {
    ChatSendResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChatSendResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.chat.ChatSendResponse";
  }
  protected:
  explicit ChatSendResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgIdFieldNumber = 2,
    kServerTsFieldNumber = 3,
    kErrFieldNumber = 1,
  };
  // uint64 msg_id = 2;
  void clear_msg_id();
  uint64_t msg_id() const;
  void set_msg_id(uint64_t value);
  private:
  uint64_t _internal_msg_id() const;
  void _internal_set_msg_id(uint64_t value);
  public:

  // uint64 server_ts = 3;
  void clear_server_ts();
  uint64_t server_ts() const;
  void set_server_ts(uint64_t value);
  private:
  uint64_t _internal_server_ts() const;
  void _internal_set_server_ts(uint64_t value);
  public:

  // .protocol.user.ErrCode err = 1;
  void clear_err();
  ::protocol::user::ErrCode err() const;
  void set_err(::protocol::user::ErrCode value);
  private:
  ::protocol::user::ErrCode _internal_err() const;
  void _internal_set_err(::protocol::user::ErrCode value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.chat.ChatSendResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t msg_id_;
    uint64_t server_ts_;
    int err_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class ChatNotify final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.chat.ChatNotify) */ {
 public:
  inline ChatNotify() : ChatNotify(nullptr) {}
  ~ChatNotify() override;
  explicit PROTOBUF_CONSTEXPR ChatNotify(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChatNotify(const ChatNotify& from);
  ChatNotify(ChatNotify&& from) noexcept
    : ChatNotify() {
    *this = ::std::move(from);
  }

  inline ChatNotify& operator=(const ChatNotify& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatNotify& operator=(ChatNotify&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChatNotify& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChatNotify* internal_default_instance() {
    return reinterpret_cast<const ChatNotify*>(
               &_ChatNotify_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ChatNotify& a, ChatNotify& b) {
    a.Swap(&b);
  }
  inline void Swap(ChatNotify* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatNotify* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChatNotify* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChatNotify>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChatNotify& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChatNotify& from) {
    ChatNotify::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChatNotify* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.chat.ChatNotify";
  }
  protected:
  explicit ChatNotify(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgFieldNumber = 1,
  };
  // .protocol.chat.ChatMessage msg = 1;
  bool has_msg() const;
  private:
  bool _internal_has_msg() const;
  public:
  void clear_msg();
  const ::protocol::chat::ChatMessage& msg() const;
  PROTOBUF_NODISCARD ::protocol::chat::ChatMessage* release_msg();
  ::protocol::chat::ChatMessage* mutable_msg();
  void set_allocated_msg(::protocol::chat::ChatMessage* msg);
  private:
  const ::protocol::chat::ChatMessage& _internal_msg() const;
  ::protocol::chat::ChatMessage* _internal_mutable_msg();
  public:
  void unsafe_arena_set_allocated_msg(
      ::protocol::chat::ChatMessage* msg);
  ::protocol::chat::ChatMessage* unsafe_arena_release_msg();

  // @@protoc_insertion_point(class_scope:protocol.chat.ChatNotify)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::protocol::chat::ChatMessage* msg_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class ChatHistoryRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.chat.ChatHistoryRequest) */ {
 public:
  inline ChatHistoryRequest() : ChatHistoryRequest(nullptr) {}
  ~ChatHistoryRequest() override;
  explicit PROTOBUF_CONSTEXPR ChatHistoryRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChatHistoryRequest(const ChatHistoryRequest& from);
  ChatHistoryRequest(ChatHistoryRequest&& from) noexcept
    : ChatHistoryRequest() {
    *this = ::std::move(from);
  }

  inline ChatHistoryRequest& operator=(const ChatHistoryRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatHistoryRequest& operator=(ChatHistoryRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChatHistoryRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChatHistoryRequest* internal_default_instance() {
    return reinterpret_cast<const ChatHistoryRequest*>(
               &_ChatHistoryRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ChatHistoryRequest& a, ChatHistoryRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ChatHistoryRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatHistoryRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChatHistoryRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChatHistoryRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChatHistoryRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChatHistoryRequest& from) {
    ChatHistoryRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChatHistoryRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.chat.ChatHistoryRequest";
  }
  protected:
  explicit ChatHistoryRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAfterMsgIdFieldNumber = 2,
    kTargetIdFieldNumber = 1,
    kLimitFieldNumber = 3,
  };
  // uint64 after_msg_id = 2;
  void clear_after_msg_id();
  uint64_t after_msg_id() const;
  void set_after_msg_id(uint64_t value);
  private:
  uint64_t _internal_after_msg_id() const;
  void _internal_set_after_msg_id(uint64_t value);
  public:

  // uint32 target_id = 1;
  void clear_target_id();
  uint32_t target_id() const;
  void set_target_id(uint32_t value);
  private:
  uint32_t _internal_target_id() const;
  void _internal_set_target_id(uint32_t value);
  public:

  // uint32 limit = 3;
  void clear_limit();
  uint32_t limit() const;
  void set_limit(uint32_t value);
  private:
  uint32_t _internal_limit() const;
  void _internal_set_limit(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.chat.ChatHistoryRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t after_msg_id_;
    uint32_t target_id_;
    uint32_t limit_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class ChatHistoryResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.chat.ChatHistoryResponse) */ {
 public:
  inline ChatHistoryResponse() : ChatHistoryResponse(nullptr) {}
  ~ChatHistoryResponse() override;
  explicit PROTOBUF_CONSTEXPR ChatHistoryResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChatHistoryResponse(const ChatHistoryResponse& from);
  ChatHistoryResponse(ChatHistoryResponse&& from) noexcept
    : ChatHistoryResponse() {
    *this = ::std::move(from);
  }

  inline ChatHistoryResponse& operator=(const ChatHistoryResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatHistoryResponse& operator=(ChatHistoryResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChatHistoryResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChatHistoryResponse* internal_default_instance() {
    return reinterpret_cast<const ChatHistoryResponse*>(
               &_ChatHistoryResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(ChatHistoryResponse& a, ChatHistoryResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ChatHistoryResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatHistoryResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChatHistoryResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChatHistoryResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChatHistoryResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChatHistoryResponse& from) {
    ChatHistoryResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChatHistoryResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.chat.ChatHistoryResponse";
  }
  protected:
  explicit ChatHistoryResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessagesFieldNumber = 1,
    kErrFieldNumber = 2,
  };
  // repeated .protocol.chat.ChatMessage messages = 1;
  int messages_size() const;
  private:
  int _internal_messages_size() const;
  public:
  void clear_messages();
  ::protocol::chat::ChatMessage* mutable_messages(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protocol::chat::ChatMessage >*
      mutable_messages();
  private:
  const ::protocol::chat::ChatMessage& _internal_messages(int index) const;
  ::protocol::chat::ChatMessage* _internal_add_messages();
  public:
  const ::protocol::chat::ChatMessage& messages(int index) const;
  ::protocol::chat::ChatMessage* add_messages();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protocol::chat::ChatMessage >&
      messages() const;

  // .protocol.user.ErrCode err = 2;
  void clear_err();
  ::protocol::user::ErrCode err() const;
  void set_err(::protocol::user::ErrCode value);
  private:
  ::protocol::user::ErrCode _internal_err() const;
  void _internal_set_err(::protocol::user::ErrCode value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.chat.ChatHistoryResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protocol::chat::ChatMessage > messages_;
    int err_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class ChatReadAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.chat.ChatReadAck) */ {
 public:
  inline ChatReadAck() : ChatReadAck(nullptr) {}
  ~ChatReadAck() override;
  explicit PROTOBUF_CONSTEXPR ChatReadAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChatReadAck(const ChatReadAck& from);
  ChatReadAck(ChatReadAck&& from) noexcept
    : ChatReadAck() {
    *this = ::std::move(from);
  }

  inline ChatReadAck& operator=(const ChatReadAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatReadAck& operator=(ChatReadAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChatReadAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChatReadAck* internal_default_instance() {
    return reinterpret_cast<const ChatReadAck*>(
               &_ChatReadAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(ChatReadAck& a, ChatReadAck& b) {
    a.Swap(&b);
  }
  inline void Swap(ChatReadAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatReadAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChatReadAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChatReadAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChatReadAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChatReadAck& from) {
    ChatReadAck::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChatReadAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.chat.ChatReadAck";
  }
  protected:
  explicit ChatReadAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgIdFieldNumber = 1,
  };
  // uint64 msg_id = 1;
  void clear_msg_id();
  uint64_t msg_id() const;
  void set_msg_id(uint64_t value);
  private:
  uint64_t _internal_msg_id() const;
  void _internal_set_msg_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.chat.ChatReadAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t msg_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class ChatPacket final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.chat.ChatPacket) */ {
 public:
  inline ChatPacket() : ChatPacket(nullptr) {}
  ~ChatPacket() override;
  explicit PROTOBUF_CONSTEXPR ChatPacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChatPacket(const ChatPacket& from);
  ChatPacket(ChatPacket&& from) noexcept
    : ChatPacket() {
    *this = ::std::move(from);
  }

  inline ChatPacket& operator=(const ChatPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatPacket& operator=(ChatPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChatPacket& default_instance() {
    return *internal_default_instance();
  }
  enum BodyCase {
    kSendReq = 1,
    kSendResp = 2,
    kNotify = 3,
    kHistoryReq = 4,
    kHistoryResp = 5,
    kReadAck = 6,
    BODY_NOT_SET = 0,
  };

  static inline const ChatPacket* internal_default_instance() {
    return reinterpret_cast<const ChatPacket*>(
               &_ChatPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(ChatPacket& a, ChatPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(ChatPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatPacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChatPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChatPacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChatPacket& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChatPacket& from) {
    ChatPacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChatPacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.chat.ChatPacket";
  }
  protected:
  explicit ChatPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSendReqFieldNumber = 1,
    kSendRespFieldNumber = 2,
    kNotifyFieldNumber = 3,
    kHistoryReqFieldNumber = 4,
    kHistoryRespFieldNumber = 5,
    kReadAckFieldNumber = 6,
  };
  // .protocol.chat.ChatSendRequest send_req = 1;
  bool has_send_req() const;
  private:
  bool _internal_has_send_req() const;
  public:
  void clear_send_req();
  const ::protocol::chat::ChatSendRequest& send_req() const;
  PROTOBUF_NODISCARD ::protocol::chat::ChatSendRequest* release_send_req();
  ::protocol::chat::ChatSendRequest* mutable_send_req();
  void set_allocated_send_req(::protocol::chat::ChatSendRequest* send_req);
  private:
  const ::protocol::chat::ChatSendRequest& _internal_send_req() const;
  ::protocol::chat::ChatSendRequest* _internal_mutable_send_req();
  public:
  void unsafe_arena_set_allocated_send_req(
      ::protocol::chat::ChatSendRequest* send_req);
  ::protocol::chat::ChatSendRequest* unsafe_arena_release_send_req();

  // .protocol.chat.ChatSendResponse send_resp = 2;
  bool has_send_resp() const;
  private:
  bool _internal_has_send_resp() const;
  public:
  void clear_send_resp();
  const ::protocol::chat::ChatSendResponse& send_resp() const;
  PROTOBUF_NODISCARD ::protocol::chat::ChatSendResponse* release_send_resp();
  ::protocol::chat::ChatSendResponse* mutable_send_resp();
  void set_allocated_send_resp(::protocol::chat::ChatSendResponse* send_resp);
  private:
  const ::protocol::chat::ChatSendResponse& _internal_send_resp() const;
  ::protocol::chat::ChatSendResponse* _internal_mutable_send_resp();
  public:
  void unsafe_arena_set_allocated_send_resp(
      ::protocol::chat::ChatSendResponse* send_resp);
  ::protocol::chat::ChatSendResponse* unsafe_arena_release_send_resp();

  // .protocol.chat.ChatNotify notify = 3;
  bool has_notify() const;
  private:
  bool _internal_has_notify() const;
  public:
  void clear_notify();
  const ::protocol::chat::ChatNotify& notify() const;
  PROTOBUF_NODISCARD ::protocol::chat::ChatNotify* release_notify();
  ::protocol::chat::ChatNotify* mutable_notify();
  void set_allocated_notify(::protocol::chat::ChatNotify* notify);
  private:
  const ::protocol::chat::ChatNotify& _internal_notify() const;
  ::protocol::chat::ChatNotify* _internal_mutable_notify();
  public:
  void unsafe_arena_set_allocated_notify(
      ::protocol::chat::ChatNotify* notify);
  ::protocol::chat::ChatNotify* unsafe_arena_release_notify();

  // .protocol.chat.ChatHistoryRequest history_req = 4;
  bool has_history_req() const;
  private:
  bool _internal_has_history_req() const;
  public:
  void clear_history_req();
  const ::protocol::chat::ChatHistoryRequest& history_req() const;
  PROTOBUF_NODISCARD ::protocol::chat::ChatHistoryRequest* release_history_req();
  ::protocol::chat::ChatHistoryRequest* mutable_history_req();
  void set_allocated_history_req(::protocol::chat::ChatHistoryRequest* history_req);
  private:
  const ::protocol::chat::ChatHistoryRequest& _internal_history_req() const;
  ::protocol::chat::ChatHistoryRequest* _internal_mutable_history_req();
  public:
  void unsafe_arena_set_allocated_history_req(
      ::protocol::chat::ChatHistoryRequest* history_req);
  ::protocol::chat::ChatHistoryRequest* unsafe_arena_release_history_req();

  // .protocol.chat.ChatHistoryResponse history_resp = 5;
  bool has_history_resp() const;
  private:
  bool _internal_has_history_resp() const;
  public:
  void clear_history_resp();
  const ::protocol::chat::ChatHistoryResponse& history_resp() const;
  PROTOBUF_NODISCARD ::protocol::chat::ChatHistoryResponse* release_history_resp();
  ::protocol::chat::ChatHistoryResponse* mutable_history_resp();
  void set_allocated_history_resp(::protocol::chat::ChatHistoryResponse* history_resp);
  private:
  const ::protocol::chat::ChatHistoryResponse& _internal_history_resp() const;
  ::protocol::chat::ChatHistoryResponse* _internal_mutable_history_resp();
  public:
  void unsafe_arena_set_allocated_history_resp(
      ::protocol::chat::ChatHistoryResponse* history_resp);
  ::protocol::chat::ChatHistoryResponse* unsafe_arena_release_history_resp();

  // .protocol.chat.ChatReadAck read_ack = 6;
  bool has_read_ack() const;
  private:
  bool _internal_has_read_ack() const;
  public:
  void clear_read_ack();
  const ::protocol::chat::ChatReadAck& read_ack() const;
  PROTOBUF_NODISCARD ::protocol::chat::ChatReadAck* release_read_ack();
  ::protocol::chat::ChatReadAck* mutable_read_ack();
  void set_allocated_read_ack(::protocol::chat::ChatReadAck* read_ack);
  private:
  const ::protocol::chat::ChatReadAck& _internal_read_ack() const;
  ::protocol::chat::ChatReadAck* _internal_mutable_read_ack();
  public:
  void unsafe_arena_set_allocated_read_ack(
      ::protocol::chat::ChatReadAck* read_ack);
  ::protocol::chat::ChatReadAck* unsafe_arena_release_read_ack();

  void clear_body();
  BodyCase body_case() const;
  // @@protoc_insertion_point(class_scope:protocol.chat.ChatPacket)
 private:
  class _Internal;
  void set_has_send_req();
  void set_has_send_resp();
  void set_has_notify();
  void set_has_history_req();
  void set_has_history_resp();
  void set_has_read_ack();

  inline bool has_body() const;
  inline void clear_has_body();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union BodyUnion {
      constexpr BodyUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::protocol::chat::ChatSendRequest* send_req_;
      ::protocol::chat::ChatSendResponse* send_resp_;
      ::protocol::chat::ChatNotify* notify_;
      ::protocol::chat::ChatHistoryRequest* history_req_;
      ::protocol::chat::ChatHistoryResponse* history_resp_;
      ::protocol::chat::ChatReadAck* read_ack_;
    } body_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ChatMessage

// uint64 msg_id = 1;
inline void ChatMessage::clear_msg_id() {
  _impl_.msg_id_ = uint64_t{0u};
}
inline uint64_t ChatMessage::_internal_msg_id() const {
  return _impl_.msg_id_;
}
inline uint64_t ChatMessage::msg_id() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatMessage.msg_id)
  return _internal_msg_id();
}
inline void ChatMessage::_internal_set_msg_id(uint64_t value) {
  
  _impl_.msg_id_ = value;
}
inline void ChatMessage::set_msg_id(uint64_t value) {
  _internal_set_msg_id(value);
  // @@protoc_insertion_point(field_set:protocol.chat.ChatMessage.msg_id)
}

// uint32 from_id = 2;
inline void ChatMessage::clear_from_id() {
  _impl_.from_id_ = 0u;
}
inline uint32_t ChatMessage::_internal_from_id() const {
  return _impl_.from_id_;
}
inline uint32_t ChatMessage::from_id() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatMessage.from_id)
  return _internal_from_id();
}
inline void ChatMessage::_internal_set_from_id(uint32_t value) {
  
  _impl_.from_id_ = value;
}
inline void ChatMessage::set_from_id(uint32_t value) {
  _internal_set_from_id(value);
  // @@protoc_insertion_point(field_set:protocol.chat.ChatMessage.from_id)
}

// uint32 to_id = 3;
inline void ChatMessage::clear_to_id() {
  _impl_.to_id_ = 0u;
}
inline uint32_t ChatMessage::_internal_to_id() const {
  return _impl_.to_id_;
}
inline uint32_t ChatMessage::to_id() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatMessage.to_id)
  return _internal_to_id();
}
inline void ChatMessage::_internal_set_to_id(uint32_t value) {
  
  _impl_.to_id_ = value;
}
inline void ChatMessage::set_to_id(uint32_t value) {
  _internal_set_to_id(value);
  // @@protoc_insertion_point(field_set:protocol.chat.ChatMessage.to_id)
}

// .protocol.chat.TargetType to_type = 4;
inline void ChatMessage::clear_to_type() {
  _impl_.to_type_ = 0;
}
inline ::protocol::chat::TargetType ChatMessage::_internal_to_type() const {
  return static_cast< ::protocol::chat::TargetType >(_impl_.to_type_);
}
inline ::protocol::chat::TargetType ChatMessage::to_type() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatMessage.to_type)
  return _internal_to_type();
}
inline void ChatMessage::_internal_set_to_type(::protocol::chat::TargetType value) {
  
  _impl_.to_type_ = value;
}
inline void ChatMessage::set_to_type(::protocol::chat::TargetType value) {
  _internal_set_to_type(value);
  // @@protoc_insertion_point(field_set:protocol.chat.ChatMessage.to_type)
}

// string content = 5;
inline void ChatMessage::clear_content() {
  _impl_.content_.ClearToEmpty();
}
inline const std::string& ChatMessage::content() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatMessage.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatMessage::set_content(ArgT0&& arg0, ArgT... args) {
 
 _impl_.content_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protocol.chat.ChatMessage.content)
}
inline std::string* ChatMessage::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:protocol.chat.ChatMessage.content)
  return _s;
}
inline const std::string& ChatMessage::_internal_content() const {
  return _impl_.content_.Get();
}
inline void ChatMessage::_internal_set_content(const std::string& value) {
  
  _impl_.content_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatMessage::_internal_mutable_content() {
  
  return _impl_.content_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatMessage::release_content() {
  // @@protoc_insertion_point(field_release:protocol.chat.ChatMessage.content)
  return _impl_.content_.Release();
}
inline void ChatMessage::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  _impl_.content_.SetAllocated(content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protocol.chat.ChatMessage.content)
}

// uint64 ts = 6;
inline void ChatMessage::clear_ts() {
  _impl_.ts_ = uint64_t{0u};
}
inline uint64_t ChatMessage::_internal_ts() const {
  return _impl_.ts_;
}
inline uint64_t ChatMessage::ts() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatMessage.ts)
  return _internal_ts();
}
inline void ChatMessage::_internal_set_ts(uint64_t value) {
  
  _impl_.ts_ = value;
}
inline void ChatMessage::set_ts(uint64_t value) {
  _internal_set_ts(value);
  // @@protoc_insertion_point(field_set:protocol.chat.ChatMessage.ts)
}

// -------------------------------------------------------------------

// ChatSendRequest

// uint32 to_id = 1;
inline void ChatSendRequest::clear_to_id() {
  _impl_.to_id_ = 0u;
}
inline uint32_t ChatSendRequest::_internal_to_id() const {
  return _impl_.to_id_;
}
inline uint32_t ChatSendRequest::to_id() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatSendRequest.to_id)
  return _internal_to_id();
}
inline void ChatSendRequest::_internal_set_to_id(uint32_t value) {
  
  _impl_.to_id_ = value;
}
inline void ChatSendRequest::set_to_id(uint32_t value) {
  _internal_set_to_id(value);
  // @@protoc_insertion_point(field_set:protocol.chat.ChatSendRequest.to_id)
}

// string content = 2;
inline void ChatSendRequest::clear_content() {
  _impl_.content_.ClearToEmpty();
}
inline const std::string& ChatSendRequest::content() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatSendRequest.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatSendRequest::set_content(ArgT0&& arg0, ArgT... args) {
 
 _impl_.content_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protocol.chat.ChatSendRequest.content)
}
inline std::string* ChatSendRequest::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:protocol.chat.ChatSendRequest.content)
  return _s;
}
inline const std::string& ChatSendRequest::_internal_content() const {
  return _impl_.content_.Get();
}
inline void ChatSendRequest::_internal_set_content(const std::string& value) {
  
  _impl_.content_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatSendRequest::_internal_mutable_content() {
  
  return _impl_.content_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatSendRequest::release_content() {
  // @@protoc_insertion_point(field_release:protocol.chat.ChatSendRequest.content)
  return _impl_.content_.Release();
}
inline void ChatSendRequest::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  _impl_.content_.SetAllocated(content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protocol.chat.ChatSendRequest.content)
}

// uint64 client_ts = 3;
inline void ChatSendRequest::clear_client_ts() {
  _impl_.client_ts_ = uint64_t{0u};
}
inline uint64_t ChatSendRequest::_internal_client_ts() const {
  return _impl_.client_ts_;
}
inline uint64_t ChatSendRequest::client_ts() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatSendRequest.client_ts)
  return _internal_client_ts();
}
inline void ChatSendRequest::_internal_set_client_ts(uint64_t value) {
  
  _impl_.client_ts_ = value;
}
inline void ChatSendRequest::set_client_ts(uint64_t value) {
  _internal_set_client_ts(value);
  // @@protoc_insertion_point(field_set:protocol.chat.ChatSendRequest.client_ts)
}

// -------------------------------------------------------------------

// ChatSendResponse

// .protocol.user.ErrCode err = 1;
inline void ChatSendResponse::clear_err() {
  _impl_.err_ = 0;
}
inline ::protocol::user::ErrCode ChatSendResponse::_internal_err() const {
  return static_cast< ::protocol::user::ErrCode >(_impl_.err_);
}
inline ::protocol::user::ErrCode ChatSendResponse::err() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatSendResponse.err)
  return _internal_err();
}
inline void ChatSendResponse::_internal_set_err(::protocol::user::ErrCode value) {
  
  _impl_.err_ = value;
}
inline void ChatSendResponse::set_err(::protocol::user::ErrCode value) {
  _internal_set_err(value);
  // @@protoc_insertion_point(field_set:protocol.chat.ChatSendResponse.err)
}

// uint64 msg_id = 2;
inline void ChatSendResponse::clear_msg_id() {
  _impl_.msg_id_ = uint64_t{0u};
}
inline uint64_t ChatSendResponse::_internal_msg_id() const {
  return _impl_.msg_id_;
}
inline uint64_t ChatSendResponse::msg_id() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatSendResponse.msg_id)
  return _internal_msg_id();
}
inline void ChatSendResponse::_internal_set_msg_id(uint64_t value) {
  
  _impl_.msg_id_ = value;
}
inline void ChatSendResponse::set_msg_id(uint64_t value) {
  _internal_set_msg_id(value);
  // @@protoc_insertion_point(field_set:protocol.chat.ChatSendResponse.msg_id)
}

// uint64 server_ts = 3;
inline void ChatSendResponse::clear_server_ts() {
  _impl_.server_ts_ = uint64_t{0u};
}
inline uint64_t ChatSendResponse::_internal_server_ts() const {
  return _impl_.server_ts_;
}
inline uint64_t ChatSendResponse::server_ts() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatSendResponse.server_ts)
  return _internal_server_ts();
}
inline void ChatSendResponse::_internal_set_server_ts(uint64_t value) {
  
  _impl_.server_ts_ = value;
}
inline void ChatSendResponse::set_server_ts(uint64_t value) {
  _internal_set_server_ts(value);
  // @@protoc_insertion_point(field_set:protocol.chat.ChatSendResponse.server_ts)
}

// -------------------------------------------------------------------

// ChatNotify

// .protocol.chat.ChatMessage msg = 1;
inline bool ChatNotify::_internal_has_msg() const {
  return this != internal_default_instance() && _impl_.msg_ != nullptr;
}
inline bool ChatNotify::has_msg() const {
  return _internal_has_msg();
}
inline void ChatNotify::clear_msg() {
  if (GetArenaForAllocation() == nullptr && _impl_.msg_ != nullptr) {
    delete _impl_.msg_;
  }
  _impl_.msg_ = nullptr;
}
inline const ::protocol::chat::ChatMessage& ChatNotify::_internal_msg() const {
  const ::protocol::chat::ChatMessage* p = _impl_.msg_;
  return p != nullptr ? *p : reinterpret_cast<const ::protocol::chat::ChatMessage&>(
      ::protocol::chat::_ChatMessage_default_instance_);
}
inline const ::protocol::chat::ChatMessage& ChatNotify::msg() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatNotify.msg)
  return _internal_msg();
}
inline void ChatNotify::unsafe_arena_set_allocated_msg(
    ::protocol::chat::ChatMessage* msg) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.msg_);
  }
  _impl_.msg_ = msg;
  if (msg) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protocol.chat.ChatNotify.msg)
}
inline ::protocol::chat::ChatMessage* ChatNotify::release_msg() {
  
  ::protocol::chat::ChatMessage* temp = _impl_.msg_;
  _impl_.msg_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::protocol::chat::ChatMessage* ChatNotify::unsafe_arena_release_msg() {
  // @@protoc_insertion_point(field_release:protocol.chat.ChatNotify.msg)
  
  ::protocol::chat::ChatMessage* temp = _impl_.msg_;
  _impl_.msg_ = nullptr;
  return temp;
}
inline ::protocol::chat::ChatMessage* ChatNotify::_internal_mutable_msg() {
  
  if (_impl_.msg_ == nullptr) {
    auto* p = CreateMaybeMessage<::protocol::chat::ChatMessage>(GetArenaForAllocation());
    _impl_.msg_ = p;
  }
  return _impl_.msg_;
}
inline ::protocol::chat::ChatMessage* ChatNotify::mutable_msg() {
  ::protocol::chat::ChatMessage* _msg = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:protocol.chat.ChatNotify.msg)
  return _msg;
}
inline void ChatNotify::set_allocated_msg(::protocol::chat::ChatMessage* msg) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.msg_;
  }
  if (msg) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(msg);
    if (message_arena != submessage_arena) {
      msg = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, msg, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.msg_ = msg;
  // @@protoc_insertion_point(field_set_allocated:protocol.chat.ChatNotify.msg)
}

// -------------------------------------------------------------------

// ChatHistoryRequest

// uint32 target_id = 1;
inline void ChatHistoryRequest::clear_target_id() {
  _impl_.target_id_ = 0u;
}
inline uint32_t ChatHistoryRequest::_internal_target_id() const {
  return _impl_.target_id_;
}
inline uint32_t ChatHistoryRequest::target_id() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatHistoryRequest.target_id)
  return _internal_target_id();
}
inline void ChatHistoryRequest::_internal_set_target_id(uint32_t value) {
  
  _impl_.target_id_ = value;
}
inline void ChatHistoryRequest::set_target_id(uint32_t value) {
  _internal_set_target_id(value);
  // @@protoc_insertion_point(field_set:protocol.chat.ChatHistoryRequest.target_id)
}

// uint64 after_msg_id = 2;
inline void ChatHistoryRequest::clear_after_msg_id() {
  _impl_.after_msg_id_ = uint64_t{0u};
}
inline uint64_t ChatHistoryRequest::_internal_after_msg_id() const {
  return _impl_.after_msg_id_;
}
inline uint64_t ChatHistoryRequest::after_msg_id() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatHistoryRequest.after_msg_id)
  return _internal_after_msg_id();
}
inline void ChatHistoryRequest::_internal_set_after_msg_id(uint64_t value) {
  
  _impl_.after_msg_id_ = value;
}
inline void ChatHistoryRequest::set_after_msg_id(uint64_t value) {
  _internal_set_after_msg_id(value);
  // @@protoc_insertion_point(field_set:protocol.chat.ChatHistoryRequest.after_msg_id)
}

// uint32 limit = 3;
inline void ChatHistoryRequest::clear_limit() {
  _impl_.limit_ = 0u;
}
inline uint32_t ChatHistoryRequest::_internal_limit() const {
  return _impl_.limit_;
}
inline uint32_t ChatHistoryRequest::limit() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatHistoryRequest.limit)
  return _internal_limit();
}
inline void ChatHistoryRequest::_internal_set_limit(uint32_t value) {
  
  _impl_.limit_ = value;
}
inline void ChatHistoryRequest::set_limit(uint32_t value) {
  _internal_set_limit(value);
  // @@protoc_insertion_point(field_set:protocol.chat.ChatHistoryRequest.limit)
}

// -------------------------------------------------------------------

// ChatHistoryResponse

// repeated .protocol.chat.ChatMessage messages = 1;
inline int ChatHistoryResponse::_internal_messages_size() const {
  return _impl_.messages_.size();
}
inline int ChatHistoryResponse::messages_size() const {
  return _internal_messages_size();
}
inline void ChatHistoryResponse::clear_messages() {
  _impl_.messages_.Clear();
}
inline ::protocol::chat::ChatMessage* ChatHistoryResponse::mutable_messages(int index) {
  // @@protoc_insertion_point(field_mutable:protocol.chat.ChatHistoryResponse.messages)
  return _impl_.messages_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protocol::chat::ChatMessage >*
ChatHistoryResponse::mutable_messages() {
  // @@protoc_insertion_point(field_mutable_list:protocol.chat.ChatHistoryResponse.messages)
  return &_impl_.messages_;
}
inline const ::protocol::chat::ChatMessage& ChatHistoryResponse::_internal_messages(int index) const {
  return _impl_.messages_.Get(index);
}
inline const ::protocol::chat::ChatMessage& ChatHistoryResponse::messages(int index) const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatHistoryResponse.messages)
  return _internal_messages(index);
}
inline ::protocol::chat::ChatMessage* ChatHistoryResponse::_internal_add_messages() {
  return _impl_.messages_.Add();
}
inline ::protocol::chat::ChatMessage* ChatHistoryResponse::add_messages() {
  ::protocol::chat::ChatMessage* _add = _internal_add_messages();
  // @@protoc_insertion_point(field_add:protocol.chat.ChatHistoryResponse.messages)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protocol::chat::ChatMessage >&
ChatHistoryResponse::messages() const {
  // @@protoc_insertion_point(field_list:protocol.chat.ChatHistoryResponse.messages)
  return _impl_.messages_;
}

// .protocol.user.ErrCode err = 2;
inline void ChatHistoryResponse::clear_err() {
  _impl_.err_ = 0;
}
inline ::protocol::user::ErrCode ChatHistoryResponse::_internal_err() const {
  return static_cast< ::protocol::user::ErrCode >(_impl_.err_);
}
inline ::protocol::user::ErrCode ChatHistoryResponse::err() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatHistoryResponse.err)
  return _internal_err();
}
inline void ChatHistoryResponse::_internal_set_err(::protocol::user::ErrCode value) {
  
  _impl_.err_ = value;
}
inline void ChatHistoryResponse::set_err(::protocol::user::ErrCode value) {
  _internal_set_err(value);
  // @@protoc_insertion_point(field_set:protocol.chat.ChatHistoryResponse.err)
}

// -------------------------------------------------------------------

// ChatReadAck

// uint64 msg_id = 1;
inline void ChatReadAck::clear_msg_id() {
  _impl_.msg_id_ = uint64_t{0u};
}
inline uint64_t ChatReadAck::_internal_msg_id() const {
  return _impl_.msg_id_;
}
inline uint64_t ChatReadAck::msg_id() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatReadAck.msg_id)
  return _internal_msg_id();
}
inline void ChatReadAck::_internal_set_msg_id(uint64_t value) {
  
  _impl_.msg_id_ = value;
}
inline void ChatReadAck::set_msg_id(uint64_t value) {
  _internal_set_msg_id(value);
  // @@protoc_insertion_point(field_set:protocol.chat.ChatReadAck.msg_id)
}

// -------------------------------------------------------------------

// ChatPacket

// .protocol.chat.ChatSendRequest send_req = 1;
inline bool ChatPacket::_internal_has_send_req() const {
  return body_case() == kSendReq;
}
inline bool ChatPacket::has_send_req() const {
  return _internal_has_send_req();
}
inline void ChatPacket::set_has_send_req() {
  _impl_._oneof_case_[0] = kSendReq;
}
inline void ChatPacket::clear_send_req() {
  if (_internal_has_send_req()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.send_req_;
    }
    clear_has_body();
  }
}
inline ::protocol::chat::ChatSendRequest* ChatPacket::release_send_req() {
  // @@protoc_insertion_point(field_release:protocol.chat.ChatPacket.send_req)
  if (_internal_has_send_req()) {
    clear_has_body();
    ::protocol::chat::ChatSendRequest* temp = _impl_.body_.send_req_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.send_req_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::protocol::chat::ChatSendRequest& ChatPacket::_internal_send_req() const {
  return _internal_has_send_req()
      ? *_impl_.body_.send_req_
      : reinterpret_cast< ::protocol::chat::ChatSendRequest&>(::protocol::chat::_ChatSendRequest_default_instance_);
}
inline const ::protocol::chat::ChatSendRequest& ChatPacket::send_req() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatPacket.send_req)
  return _internal_send_req();
}
inline ::protocol::chat::ChatSendRequest* ChatPacket::unsafe_arena_release_send_req() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protocol.chat.ChatPacket.send_req)
  if (_internal_has_send_req()) {
    clear_has_body();
    ::protocol::chat::ChatSendRequest* temp = _impl_.body_.send_req_;
    _impl_.body_.send_req_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ChatPacket::unsafe_arena_set_allocated_send_req(::protocol::chat::ChatSendRequest* send_req) {
  clear_body();
  if (send_req) {
    set_has_send_req();
    _impl_.body_.send_req_ = send_req;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protocol.chat.ChatPacket.send_req)
}
inline ::protocol::chat::ChatSendRequest* ChatPacket::_internal_mutable_send_req() {
  if (!_internal_has_send_req()) {
    clear_body();
    set_has_send_req();
    _impl_.body_.send_req_ = CreateMaybeMessage< ::protocol::chat::ChatSendRequest >(GetArenaForAllocation());
  }
  return _impl_.body_.send_req_;
}
inline ::protocol::chat::ChatSendRequest* ChatPacket::mutable_send_req() {
  ::protocol::chat::ChatSendRequest* _msg = _internal_mutable_send_req();
  // @@protoc_insertion_point(field_mutable:protocol.chat.ChatPacket.send_req)
  return _msg;
}

// .protocol.chat.ChatSendResponse send_resp = 2;
inline bool ChatPacket::_internal_has_send_resp() const {
  return body_case() == kSendResp;
}
inline bool ChatPacket::has_send_resp() const {
  return _internal_has_send_resp();
}
inline void ChatPacket::set_has_send_resp() {
  _impl_._oneof_case_[0] = kSendResp;
}
inline void ChatPacket::clear_send_resp() {
  if (_internal_has_send_resp()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.send_resp_;
    }
    clear_has_body();
  }
}
inline ::protocol::chat::ChatSendResponse* ChatPacket::release_send_resp() {
  // @@protoc_insertion_point(field_release:protocol.chat.ChatPacket.send_resp)
  if (_internal_has_send_resp()) {
    clear_has_body();
    ::protocol::chat::ChatSendResponse* temp = _impl_.body_.send_resp_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.send_resp_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::protocol::chat::ChatSendResponse& ChatPacket::_internal_send_resp() const {
  return _internal_has_send_resp()
      ? *_impl_.body_.send_resp_
      : reinterpret_cast< ::protocol::chat::ChatSendResponse&>(::protocol::chat::_ChatSendResponse_default_instance_);
}
inline const ::protocol::chat::ChatSendResponse& ChatPacket::send_resp() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatPacket.send_resp)
  return _internal_send_resp();
}
inline ::protocol::chat::ChatSendResponse* ChatPacket::unsafe_arena_release_send_resp() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protocol.chat.ChatPacket.send_resp)
  if (_internal_has_send_resp()) {
    clear_has_body();
    ::protocol::chat::ChatSendResponse* temp = _impl_.body_.send_resp_;
    _impl_.body_.send_resp_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ChatPacket::unsafe_arena_set_allocated_send_resp(::protocol::chat::ChatSendResponse* send_resp) {
  clear_body();
  if (send_resp) {
    set_has_send_resp();
    _impl_.body_.send_resp_ = send_resp;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protocol.chat.ChatPacket.send_resp)
}
inline ::protocol::chat::ChatSendResponse* ChatPacket::_internal_mutable_send_resp() {
  if (!_internal_has_send_resp()) {
    clear_body();
    set_has_send_resp();
    _impl_.body_.send_resp_ = CreateMaybeMessage< ::protocol::chat::ChatSendResponse >(GetArenaForAllocation());
  }
  return _impl_.body_.send_resp_;
}
inline ::protocol::chat::ChatSendResponse* ChatPacket::mutable_send_resp() {
  ::protocol::chat::ChatSendResponse* _msg = _internal_mutable_send_resp();
  // @@protoc_insertion_point(field_mutable:protocol.chat.ChatPacket.send_resp)
  return _msg;
}

// .protocol.chat.ChatNotify notify = 3;
inline bool ChatPacket::_internal_has_notify() const {
  return body_case() == kNotify;
}
inline bool ChatPacket::has_notify() const {
  return _internal_has_notify();
}
inline void ChatPacket::set_has_notify() {
  _impl_._oneof_case_[0] = kNotify;
}
inline void ChatPacket::clear_notify() {
  if (_internal_has_notify()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.notify_;
    }
    clear_has_body();
  }
}
inline ::protocol::chat::ChatNotify* ChatPacket::release_notify() {
  // @@protoc_insertion_point(field_release:protocol.chat.ChatPacket.notify)
  if (_internal_has_notify()) {
    clear_has_body();
    ::protocol::chat::ChatNotify* temp = _impl_.body_.notify_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.notify_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::protocol::chat::ChatNotify& ChatPacket::_internal_notify() const {
  return _internal_has_notify()
      ? *_impl_.body_.notify_
      : reinterpret_cast< ::protocol::chat::ChatNotify&>(::protocol::chat::_ChatNotify_default_instance_);
}
inline const ::protocol::chat::ChatNotify& ChatPacket::notify() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatPacket.notify)
  return _internal_notify();
}
inline ::protocol::chat::ChatNotify* ChatPacket::unsafe_arena_release_notify() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protocol.chat.ChatPacket.notify)
  if (_internal_has_notify()) {
    clear_has_body();
    ::protocol::chat::ChatNotify* temp = _impl_.body_.notify_;
    _impl_.body_.notify_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ChatPacket::unsafe_arena_set_allocated_notify(::protocol::chat::ChatNotify* notify) {
  clear_body();
  if (notify) {
    set_has_notify();
    _impl_.body_.notify_ = notify;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protocol.chat.ChatPacket.notify)
}
inline ::protocol::chat::ChatNotify* ChatPacket::_internal_mutable_notify() {
  if (!_internal_has_notify()) {
    clear_body();
    set_has_notify();
    _impl_.body_.notify_ = CreateMaybeMessage< ::protocol::chat::ChatNotify >(GetArenaForAllocation());
  }
  return _impl_.body_.notify_;
}
inline ::protocol::chat::ChatNotify* ChatPacket::mutable_notify() {
  ::protocol::chat::ChatNotify* _msg = _internal_mutable_notify();
  // @@protoc_insertion_point(field_mutable:protocol.chat.ChatPacket.notify)
  return _msg;
}

// .protocol.chat.ChatHistoryRequest history_req = 4;
inline bool ChatPacket::_internal_has_history_req() const {
  return body_case() == kHistoryReq;
}
inline bool ChatPacket::has_history_req() const {
  return _internal_has_history_req();
}
inline void ChatPacket::set_has_history_req() {
  _impl_._oneof_case_[0] = kHistoryReq;
}
inline void ChatPacket::clear_history_req() {
  if (_internal_has_history_req()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.history_req_;
    }
    clear_has_body();
  }
}
inline ::protocol::chat::ChatHistoryRequest* ChatPacket::release_history_req() {
  // @@protoc_insertion_point(field_release:protocol.chat.ChatPacket.history_req)
  if (_internal_has_history_req()) {
    clear_has_body();
    ::protocol::chat::ChatHistoryRequest* temp = _impl_.body_.history_req_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.history_req_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::protocol::chat::ChatHistoryRequest& ChatPacket::_internal_history_req() const {
  return _internal_has_history_req()
      ? *_impl_.body_.history_req_
      : reinterpret_cast< ::protocol::chat::ChatHistoryRequest&>(::protocol::chat::_ChatHistoryRequest_default_instance_);
}
inline const ::protocol::chat::ChatHistoryRequest& ChatPacket::history_req() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatPacket.history_req)
  return _internal_history_req();
}
inline ::protocol::chat::ChatHistoryRequest* ChatPacket::unsafe_arena_release_history_req() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protocol.chat.ChatPacket.history_req)
  if (_internal_has_history_req()) {
    clear_has_body();
    ::protocol::chat::ChatHistoryRequest* temp = _impl_.body_.history_req_;
    _impl_.body_.history_req_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ChatPacket::unsafe_arena_set_allocated_history_req(::protocol::chat::ChatHistoryRequest* history_req) {
  clear_body();
  if (history_req) {
    set_has_history_req();
    _impl_.body_.history_req_ = history_req;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protocol.chat.ChatPacket.history_req)
}
inline ::protocol::chat::ChatHistoryRequest* ChatPacket::_internal_mutable_history_req() {
  if (!_internal_has_history_req()) {
    clear_body();
    set_has_history_req();
    _impl_.body_.history_req_ = CreateMaybeMessage< ::protocol::chat::ChatHistoryRequest >(GetArenaForAllocation());
  }
  return _impl_.body_.history_req_;
}
inline ::protocol::chat::ChatHistoryRequest* ChatPacket::mutable_history_req() {
  ::protocol::chat::ChatHistoryRequest* _msg = _internal_mutable_history_req();
  // @@protoc_insertion_point(field_mutable:protocol.chat.ChatPacket.history_req)
  return _msg;
}

// .protocol.chat.ChatHistoryResponse history_resp = 5;
inline bool ChatPacket::_internal_has_history_resp() const {
  return body_case() == kHistoryResp;
}
inline bool ChatPacket::has_history_resp() const {
  return _internal_has_history_resp();
}
inline void ChatPacket::set_has_history_resp() {
  _impl_._oneof_case_[0] = kHistoryResp;
}
inline void ChatPacket::clear_history_resp() {
  if (_internal_has_history_resp()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.history_resp_;
    }
    clear_has_body();
  }
}
inline ::protocol::chat::ChatHistoryResponse* ChatPacket::release_history_resp() {
  // @@protoc_insertion_point(field_release:protocol.chat.ChatPacket.history_resp)
  if (_internal_has_history_resp()) {
    clear_has_body();
    ::protocol::chat::ChatHistoryResponse* temp = _impl_.body_.history_resp_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.history_resp_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::protocol::chat::ChatHistoryResponse& ChatPacket::_internal_history_resp() const {
  return _internal_has_history_resp()
      ? *_impl_.body_.history_resp_
      : reinterpret_cast< ::protocol::chat::ChatHistoryResponse&>(::protocol::chat::_ChatHistoryResponse_default_instance_);
}
inline const ::protocol::chat::ChatHistoryResponse& ChatPacket::history_resp() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatPacket.history_resp)
  return _internal_history_resp();
}
inline ::protocol::chat::ChatHistoryResponse* ChatPacket::unsafe_arena_release_history_resp() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protocol.chat.ChatPacket.history_resp)
  if (_internal_has_history_resp()) {
    clear_has_body();
    ::protocol::chat::ChatHistoryResponse* temp = _impl_.body_.history_resp_;
    _impl_.body_.history_resp_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ChatPacket::unsafe_arena_set_allocated_history_resp(::protocol::chat::ChatHistoryResponse* history_resp) {
  clear_body();
  if (history_resp) {
    set_has_history_resp();
    _impl_.body_.history_resp_ = history_resp;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protocol.chat.ChatPacket.history_resp)
}
inline ::protocol::chat::ChatHistoryResponse* ChatPacket::_internal_mutable_history_resp() {
  if (!_internal_has_history_resp()) {
    clear_body();
    set_has_history_resp();
    _impl_.body_.history_resp_ = CreateMaybeMessage< ::protocol::chat::ChatHistoryResponse >(GetArenaForAllocation());
  }
  return _impl_.body_.history_resp_;
}
inline ::protocol::chat::ChatHistoryResponse* ChatPacket::mutable_history_resp() {
  ::protocol::chat::ChatHistoryResponse* _msg = _internal_mutable_history_resp();
  // @@protoc_insertion_point(field_mutable:protocol.chat.ChatPacket.history_resp)
  return _msg;
}

// .protocol.chat.ChatReadAck read_ack = 6;
inline bool ChatPacket::_internal_has_read_ack() const {
  return body_case() == kReadAck;
}
inline bool ChatPacket::has_read_ack() const {
  return _internal_has_read_ack();
}
inline void ChatPacket::set_has_read_ack() {
  _impl_._oneof_case_[0] = kReadAck;
}
inline void ChatPacket::clear_read_ack() {
  if (_internal_has_read_ack()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.read_ack_;
    }
    clear_has_body();
  }
}
inline ::protocol::chat::ChatReadAck* ChatPacket::release_read_ack() {
  // @@protoc_insertion_point(field_release:protocol.chat.ChatPacket.read_ack)
  if (_internal_has_read_ack()) {
    clear_has_body();
    ::protocol::chat::ChatReadAck* temp = _impl_.body_.read_ack_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.read_ack_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::protocol::chat::ChatReadAck& ChatPacket::_internal_read_ack() const {
  return _internal_has_read_ack()
      ? *_impl_.body_.read_ack_
      : reinterpret_cast< ::protocol::chat::ChatReadAck&>(::protocol::chat::_ChatReadAck_default_instance_);
}
inline const ::protocol::chat::ChatReadAck& ChatPacket::read_ack() const {
  // @@protoc_insertion_point(field_get:protocol.chat.ChatPacket.read_ack)
  return _internal_read_ack();
}
inline ::protocol::chat::ChatReadAck* ChatPacket::unsafe_arena_release_read_ack() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protocol.chat.ChatPacket.read_ack)
  if (_internal_has_read_ack()) {
    clear_has_body();
    ::protocol::chat::ChatReadAck* temp = _impl_.body_.read_ack_;
    _impl_.body_.read_ack_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ChatPacket::unsafe_arena_set_allocated_read_ack(::protocol::chat::ChatReadAck* read_ack) {
  clear_body();
  if (read_ack) {
    set_has_read_ack();
    _impl_.body_.read_ack_ = read_ack;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protocol.chat.ChatPacket.read_ack)
}
inline ::protocol::chat::ChatReadAck* ChatPacket::_internal_mutable_read_ack() {
  if (!_internal_has_read_ack()) {
    clear_body();
    set_has_read_ack();
    _impl_.body_.read_ack_ = CreateMaybeMessage< ::protocol::chat::ChatReadAck >(GetArenaForAllocation());
  }
  return _impl_.body_.read_ack_;
}
inline ::protocol::chat::ChatReadAck* ChatPacket::mutable_read_ack() {
  ::protocol::chat::ChatReadAck* _msg = _internal_mutable_read_ack();
  // @@protoc_insertion_point(field_mutable:protocol.chat.ChatPacket.read_ack)
  return _msg;
}

inline bool ChatPacket::has_body() const {
  return body_case() != BODY_NOT_SET;
}
inline void ChatPacket::clear_has_body() {
  _impl_._oneof_case_[0] = BODY_NOT_SET;
}
inline ChatPacket::BodyCase ChatPacket::body_case() const {
  return ChatPacket::BodyCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace chat
}  // namespace protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::protocol::chat::TargetType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protocol::chat::TargetType>() {
  return ::protocol::chat::TargetType_descriptor();
}
template <> struct is_proto_enum< ::protocol::chat::MsgType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protocol::chat::MsgType>() {
  return ::protocol::chat::MsgType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_chat_2eproto
