// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

#include "chat.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace protocol {
namespace chat {
PROTOBUF_CONSTEXPR ChatMessage::ChatMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.content_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.msg_id_)*/uint64_t{0u}
  , /*decltype(_impl_.from_id_)*/0u
  , /*decltype(_impl_.to_id_)*/0u
  , /*decltype(_impl_.ts_)*/uint64_t{0u}
  , /*decltype(_impl_.to_type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ChatMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChatMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChatMessageDefaultTypeInternal() {}
  union {
    ChatMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChatMessageDefaultTypeInternal _ChatMessage_default_instance_;
PROTOBUF_CONSTEXPR ChatSendRequest::ChatSendRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.content_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.to_id_)*/0u
  , /*decltype(_impl_.to_type_)*/0
  , /*decltype(_impl_.client_ts_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ChatSendRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChatSendRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChatSendRequestDefaultTypeInternal() {}
  union {
    ChatSendRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChatSendRequestDefaultTypeInternal _ChatSendRequest_default_instance_;
PROTOBUF_CONSTEXPR ChatSendResponse::ChatSendResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.msg_id_)*/uint64_t{0u}
  , /*decltype(_impl_.server_ts_)*/uint64_t{0u}
  , /*decltype(_impl_.err_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ChatSendResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChatSendResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChatSendResponseDefaultTypeInternal() {}
  union {
    ChatSendResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChatSendResponseDefaultTypeInternal _ChatSendResponse_default_instance_;
PROTOBUF_CONSTEXPR ChatNotify::ChatNotify(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.msg_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ChatNotifyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChatNotifyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChatNotifyDefaultTypeInternal() {}
  union {
    ChatNotify _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChatNotifyDefaultTypeInternal _ChatNotify_default_instance_;
PROTOBUF_CONSTEXPR ChatHistoryRequest::ChatHistoryRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.after_msg_id_)*/uint64_t{0u}
  , /*decltype(_impl_.target_id_)*/0u
  , /*decltype(_impl_.limit_)*/0u
  , /*decltype(_impl_.to_type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ChatHistoryRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChatHistoryRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChatHistoryRequestDefaultTypeInternal() {}
  union {
    ChatHistoryRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChatHistoryRequestDefaultTypeInternal _ChatHistoryRequest_default_instance_;
PROTOBUF_CONSTEXPR ChatHistoryResponse::ChatHistoryResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.messages_)*/{}
  , /*decltype(_impl_.err_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ChatHistoryResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChatHistoryResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChatHistoryResponseDefaultTypeInternal() {}
  union {
    ChatHistoryResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChatHistoryResponseDefaultTypeInternal _ChatHistoryResponse_default_instance_;
PROTOBUF_CONSTEXPR ChatReadAck::ChatReadAck(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.msg_id_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ChatReadAckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChatReadAckDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChatReadAckDefaultTypeInternal() {}
  union {
    ChatReadAck _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChatReadAckDefaultTypeInternal _ChatReadAck_default_instance_;
PROTOBUF_CONSTEXPR ChatPacket::ChatPacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.body_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct ChatPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChatPacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChatPacketDefaultTypeInternal() {}
  union {
    ChatPacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChatPacketDefaultTypeInternal _ChatPacket_default_instance_;
}  // namespace chat
}  // namespace protocol
static ::_pb::Metadata file_level_metadata_chat_2eproto[8];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_chat_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_chat_2eproto = nullptr;

const uint32_t TableStruct_chat_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatMessage, _impl_.msg_id_),
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatMessage, _impl_.from_id_),
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatMessage, _impl_.to_id_),
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatMessage, _impl_.to_type_),
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatMessage, _impl_.content_),
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatMessage, _impl_.ts_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatSendRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatSendRequest, _impl_.to_id_),
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatSendRequest, _impl_.content_),
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatSendRequest, _impl_.client_ts_),
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatSendRequest, _impl_.to_type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatSendResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatSendResponse, _impl_.err_),
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatSendResponse, _impl_.msg_id_),
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatSendResponse, _impl_.server_ts_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatNotify, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatNotify, _impl_.msg_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatHistoryRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatHistoryRequest, _impl_.target_id_),
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatHistoryRequest, _impl_.after_msg_id_),
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatHistoryRequest, _impl_.limit_),
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatHistoryRequest, _impl_.to_type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatHistoryResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatHistoryResponse, _impl_.messages_),
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatHistoryResponse, _impl_.err_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatReadAck, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatReadAck, _impl_.msg_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatPacket, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::protocol::chat::ChatPacket, _impl_.body_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::protocol::chat::ChatMessage)},
  { 12, -1, -1, sizeof(::protocol::chat::ChatSendRequest)},
  { 22, -1, -1, sizeof(::protocol::chat::ChatSendResponse)},
  { 31, -1, -1, sizeof(::protocol::chat::ChatNotify)},
  { 38, -1, -1, sizeof(::protocol::chat::ChatHistoryRequest)},
  { 48, -1, -1, sizeof(::protocol::chat::ChatHistoryResponse)},
  { 56, -1, -1, sizeof(::protocol::chat::ChatReadAck)},
  { 63, -1, -1, sizeof(::protocol::chat::ChatPacket)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::protocol::chat::_ChatMessage_default_instance_._instance,
  &::protocol::chat::_ChatSendRequest_default_instance_._instance,
  &::protocol::chat::_ChatSendResponse_default_instance_._instance,
  &::protocol::chat::_ChatNotify_default_instance_._instance,
  &::protocol::chat::_ChatHistoryRequest_default_instance_._instance,
  &::protocol::chat::_ChatHistoryResponse_default_instance_._instance,
  &::protocol::chat::_ChatReadAck_default_instance_._instance,
  &::protocol::chat::_ChatPacket_default_instance_._instance,
};

const char descriptor_table_protodef_chat_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nchat.proto\022\rprotocol.chat\032\nuser.proto\""
  "\206\001\n\013ChatMessage\022\016\n\006msg_id\030\001 \001(\004\022\017\n\007from_"
  "id\030\002 \001(\r\022\r\n\005to_id\030\003 \001(\r\022*\n\007to_type\030\004 \001(\016"
  "2\031.protocol.chat.TargetType\022\017\n\007content\030\005"
  " \001(\t\022\n\n\002ts\030\006 \001(\004\"p\n\017ChatSendRequest\022\r\n\005t"
  "o_id\030\001 \001(\r\022\017\n\007content\030\002 \001(\t\022\021\n\tclient_ts"
  "\030\003 \001(\004\022*\n\007to_type\030\004 \001(\0162\031.protocol.chat."
  "TargetType\"Z\n\020ChatSendResponse\022#\n\003err\030\001 "
  "\001(\0162\026.protocol.user.ErrCode\022\016\n\006msg_id\030\002 "
  "\001(\004\022\021\n\tserver_ts\030\003 \001(\004\"5\n\nChatNotify\022\'\n\003"
  "msg\030\001 \001(\0132\032.protocol.chat.ChatMessage\"x\n"
  "\022ChatHistoryRequest\022\021\n\ttarget_id\030\001 \001(\r\022\024"
  "\n\014after_msg_id\030\002 \001(\004\022\r\n\005limit\030\003 \001(\r\022*\n\007t"
  "o_type\030\004 \001(\0162\031.protocol.chat.TargetType\""
  "h\n\023ChatHistoryResponse\022,\n\010messages\030\001 \003(\013"
  "2\032.protocol.chat.ChatMessage\022#\n\003err\030\002 \001("
  "\0162\026.protocol.user.ErrCode\"\035\n\013ChatReadAck"
  "\022\016\n\006msg_id\030\001 \001(\004\"\321\002\n\nChatPacket\0222\n\010send_"
  "req\030\001 \001(\0132\036.protocol.chat.ChatSendReques"
  "tH\000\0224\n\tsend_resp\030\002 \001(\0132\037.protocol.chat.C"
  "hatSendResponseH\000\022+\n\006notify\030\003 \001(\0132\031.prot"
  "ocol.chat.ChatNotifyH\000\0228\n\013history_req\030\004 "
  "\001(\0132!.protocol.chat.ChatHistoryRequestH\000"
  "\022:\n\014history_resp\030\005 \001(\0132\".protocol.chat.C"
  "hatHistoryResponseH\000\022.\n\010read_ack\030\006 \001(\0132\032"
  ".protocol.chat.ChatReadAckH\000B\006\n\004body*V\n\n"
  "TargetType\022\033\n\027TARGET_TYPE_UNSPECIFIED\020\000\022"
  "\024\n\020TARGET_TYPE_USER\020\001\022\025\n\021TARGET_TYPE_GRO"
  "UP\020\002*C\n\007MsgType\022\021\n\rMSG_TYPE_TEXT\020\000\022\022\n\016MS"
  "G_TYPE_IMAGE\020\001\022\021\n\rMSG_TYPE_FILE\020\002b\006proto"
  "3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_chat_2eproto_deps[1] = {
  &::descriptor_table_user_2eproto,
};
static ::_pbi::once_flag descriptor_table_chat_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_chat_2eproto = {
    false, false, 1201, descriptor_table_protodef_chat_2eproto,
    "chat.proto",
    &descriptor_table_chat_2eproto_once, descriptor_table_chat_2eproto_deps, 1, 8,
    schemas, file_default_instances, TableStruct_chat_2eproto::offsets,
    file_level_metadata_chat_2eproto, file_level_enum_descriptors_chat_2eproto,
    file_level_service_descriptors_chat_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_chat_2eproto_getter() {
  return &descriptor_table_chat_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_chat_2eproto(&descriptor_table_chat_2eproto);
namespace protocol {
namespace chat {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TargetType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_chat_2eproto);
  return file_level_enum_descriptors_chat_2eproto[0];
}
bool TargetType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MsgType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_chat_2eproto);
  return file_level_enum_descriptors_chat_2eproto[1];
}
bool MsgType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class ChatMessage::_Internal {
 public:
};

ChatMessage::ChatMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protocol.chat.ChatMessage)
}
ChatMessage::ChatMessage(const ChatMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ChatMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.content_){}
    , decltype(_impl_.msg_id_){}
    , decltype(_impl_.from_id_){}
    , decltype(_impl_.to_id_){}
    , decltype(_impl_.ts_){}
    , decltype(_impl_.to_type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_content().empty()) {
    _this->_impl_.content_.Set(from._internal_content(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.msg_id_, &from._impl_.msg_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.to_type_) -
    reinterpret_cast<char*>(&_impl_.msg_id_)) + sizeof(_impl_.to_type_));
  // @@protoc_insertion_point(copy_constructor:protocol.chat.ChatMessage)
}

inline void ChatMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.content_){}
    , decltype(_impl_.msg_id_){uint64_t{0u}}
    , decltype(_impl_.from_id_){0u}
    , decltype(_impl_.to_id_){0u}
    , decltype(_impl_.ts_){uint64_t{0u}}
    , decltype(_impl_.to_type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ChatMessage::~ChatMessage() {
  // @@protoc_insertion_point(destructor:protocol.chat.ChatMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ChatMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.content_.Destroy();
}

void ChatMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ChatMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.chat.ChatMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.content_.ClearToEmpty();
  ::memset(&_impl_.msg_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.to_type_) -
      reinterpret_cast<char*>(&_impl_.msg_id_)) + sizeof(_impl_.to_type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ChatMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 msg_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.msg_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 from_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.from_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 to_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.to_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .protocol.chat.TargetType to_type = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_to_type(static_cast<::protocol::chat::TargetType>(val));
        } else
          goto handle_unusual;
        continue;
      // string content = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_content();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protocol.chat.ChatMessage.content"));
        } else
          goto handle_unusual;
        continue;
      // uint64 ts = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.ts_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ChatMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.chat.ChatMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 msg_id = 1;
  if (this->_internal_msg_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_msg_id(), target);
  }

  // uint32 from_id = 2;
  if (this->_internal_from_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_from_id(), target);
  }

  // uint32 to_id = 3;
  if (this->_internal_to_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_to_id(), target);
  }

  // .protocol.chat.TargetType to_type = 4;
  if (this->_internal_to_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_to_type(), target);
  }

  // string content = 5;
  if (!this->_internal_content().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_content().data(), static_cast<int>(this->_internal_content().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protocol.chat.ChatMessage.content");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_content(), target);
  }

  // uint64 ts = 6;
  if (this->_internal_ts() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(6, this->_internal_ts(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.chat.ChatMessage)
  return target;
}

size_t ChatMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.chat.ChatMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string content = 5;
  if (!this->_internal_content().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_content());
  }

  // uint64 msg_id = 1;
  if (this->_internal_msg_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_msg_id());
  }

  // uint32 from_id = 2;
  if (this->_internal_from_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_from_id());
  }

  // uint32 to_id = 3;
  if (this->_internal_to_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_to_id());
  }

  // uint64 ts = 6;
  if (this->_internal_ts() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_ts());
  }

  // .protocol.chat.TargetType to_type = 4;
  if (this->_internal_to_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_to_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ChatMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ChatMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ChatMessage::GetClassData() const { return &_class_data_; }


void ChatMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ChatMessage*>(&to_msg);
  auto& from = static_cast<const ChatMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protocol.chat.ChatMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  if (from._internal_msg_id() != 0) {
    _this->_internal_set_msg_id(from._internal_msg_id());
  }
  if (from._internal_from_id() != 0) {
    _this->_internal_set_from_id(from._internal_from_id());
  }
  if (from._internal_to_id() != 0) {
    _this->_internal_set_to_id(from._internal_to_id());
  }
  if (from._internal_ts() != 0) {
    _this->_internal_set_ts(from._internal_ts());
  }
  if (from._internal_to_type() != 0) {
    _this->_internal_set_to_type(from._internal_to_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ChatMessage::CopyFrom(const ChatMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.chat.ChatMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChatMessage::IsInitialized() const {
  return true;
}

void ChatMessage::InternalSwap(ChatMessage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.content_, lhs_arena,
      &other->_impl_.content_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ChatMessage, _impl_.to_type_)
      + sizeof(ChatMessage::_impl_.to_type_)
      - PROTOBUF_FIELD_OFFSET(ChatMessage, _impl_.msg_id_)>(
          reinterpret_cast<char*>(&_impl_.msg_id_),
          reinterpret_cast<char*>(&other->_impl_.msg_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ChatMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chat_2eproto_getter, &descriptor_table_chat_2eproto_once,
      file_level_metadata_chat_2eproto[0]);
}

// ===================================================================

class ChatSendRequest::_Internal {
 public:
};

ChatSendRequest::ChatSendRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protocol.chat.ChatSendRequest)
}
ChatSendRequest::ChatSendRequest(const ChatSendRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ChatSendRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.content_){}
    , decltype(_impl_.to_id_){}
    , decltype(_impl_.to_type_){}
    , decltype(_impl_.client_ts_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_content().empty()) {
    _this->_impl_.content_.Set(from._internal_content(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.to_id_, &from._impl_.to_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.client_ts_) -
    reinterpret_cast<char*>(&_impl_.to_id_)) + sizeof(_impl_.client_ts_));
  // @@protoc_insertion_point(copy_constructor:protocol.chat.ChatSendRequest)
}

inline void ChatSendRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.content_){}
    , decltype(_impl_.to_id_){0u}
    , decltype(_impl_.to_type_){0}
    , decltype(_impl_.client_ts_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ChatSendRequest::~ChatSendRequest() {
  // @@protoc_insertion_point(destructor:protocol.chat.ChatSendRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ChatSendRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.content_.Destroy();
}

void ChatSendRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ChatSendRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.chat.ChatSendRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.content_.ClearToEmpty();
  ::memset(&_impl_.to_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.client_ts_) -
      reinterpret_cast<char*>(&_impl_.to_id_)) + sizeof(_impl_.client_ts_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ChatSendRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 to_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.to_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string content = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_content();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protocol.chat.ChatSendRequest.content"));
        } else
          goto handle_unusual;
        continue;
      // uint64 client_ts = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.client_ts_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .protocol.chat.TargetType to_type = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_to_type(static_cast<::protocol::chat::TargetType>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ChatSendRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.chat.ChatSendRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 to_id = 1;
  if (this->_internal_to_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_to_id(), target);
  }

  // string content = 2;
  if (!this->_internal_content().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_content().data(), static_cast<int>(this->_internal_content().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protocol.chat.ChatSendRequest.content");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_content(), target);
  }

  // uint64 client_ts = 3;
  if (this->_internal_client_ts() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_client_ts(), target);
  }

  // .protocol.chat.TargetType to_type = 4;
  if (this->_internal_to_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_to_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.chat.ChatSendRequest)
  return target;
}

size_t ChatSendRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.chat.ChatSendRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string content = 2;
  if (!this->_internal_content().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_content());
  }

  // uint32 to_id = 1;
  if (this->_internal_to_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_to_id());
  }

  // .protocol.chat.TargetType to_type = 4;
  if (this->_internal_to_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_to_type());
  }

  // uint64 client_ts = 3;
  if (this->_internal_client_ts() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_client_ts());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ChatSendRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ChatSendRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ChatSendRequest::GetClassData() const { return &_class_data_; }


void ChatSendRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ChatSendRequest*>(&to_msg);
  auto& from = static_cast<const ChatSendRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protocol.chat.ChatSendRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  if (from._internal_to_id() != 0) {
    _this->_internal_set_to_id(from._internal_to_id());
  }
  if (from._internal_to_type() != 0) {
    _this->_internal_set_to_type(from._internal_to_type());
  }
  if (from._internal_client_ts() != 0) {
    _this->_internal_set_client_ts(from._internal_client_ts());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ChatSendRequest::CopyFrom(const ChatSendRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.chat.ChatSendRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChatSendRequest::IsInitialized() const {
  return true;
}

void ChatSendRequest::InternalSwap(ChatSendRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.content_, lhs_arena,
      &other->_impl_.content_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ChatSendRequest, _impl_.client_ts_)
      + sizeof(ChatSendRequest::_impl_.client_ts_)
      - PROTOBUF_FIELD_OFFSET(ChatSendRequest, _impl_.to_id_)>(
          reinterpret_cast<char*>(&_impl_.to_id_),
          reinterpret_cast<char*>(&other->_impl_.to_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ChatSendRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chat_2eproto_getter, &descriptor_table_chat_2eproto_once,
      file_level_metadata_chat_2eproto[1]);
}

// ===================================================================

class ChatSendResponse::_Internal {
 public:
};

ChatSendResponse::ChatSendResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protocol.chat.ChatSendResponse)
}
ChatSendResponse::ChatSendResponse(const ChatSendResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ChatSendResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.msg_id_){}
    , decltype(_impl_.server_ts_){}
    , decltype(_impl_.err_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.msg_id_, &from._impl_.msg_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.err_) -
    reinterpret_cast<char*>(&_impl_.msg_id_)) + sizeof(_impl_.err_));
  // @@protoc_insertion_point(copy_constructor:protocol.chat.ChatSendResponse)
}

inline void ChatSendResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.msg_id_){uint64_t{0u}}
    , decltype(_impl_.server_ts_){uint64_t{0u}}
    , decltype(_impl_.err_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ChatSendResponse::~ChatSendResponse() {
  // @@protoc_insertion_point(destructor:protocol.chat.ChatSendResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ChatSendResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ChatSendResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ChatSendResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.chat.ChatSendResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.msg_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.err_) -
      reinterpret_cast<char*>(&_impl_.msg_id_)) + sizeof(_impl_.err_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ChatSendResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .protocol.user.ErrCode err = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_err(static_cast<::protocol::user::ErrCode>(val));
        } else
          goto handle_unusual;
        continue;
      // uint64 msg_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.msg_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 server_ts = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.server_ts_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ChatSendResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.chat.ChatSendResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .protocol.user.ErrCode err = 1;
  if (this->_internal_err() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_err(), target);
  }

  // uint64 msg_id = 2;
  if (this->_internal_msg_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_msg_id(), target);
  }

  // uint64 server_ts = 3;
  if (this->_internal_server_ts() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_server_ts(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.chat.ChatSendResponse)
  return target;
}

size_t ChatSendResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.chat.ChatSendResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 msg_id = 2;
  if (this->_internal_msg_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_msg_id());
  }

  // uint64 server_ts = 3;
  if (this->_internal_server_ts() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_server_ts());
  }

  // .protocol.user.ErrCode err = 1;
  if (this->_internal_err() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_err());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ChatSendResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ChatSendResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ChatSendResponse::GetClassData() const { return &_class_data_; }


void ChatSendResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ChatSendResponse*>(&to_msg);
  auto& from = static_cast<const ChatSendResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protocol.chat.ChatSendResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_msg_id() != 0) {
    _this->_internal_set_msg_id(from._internal_msg_id());
  }
  if (from._internal_server_ts() != 0) {
    _this->_internal_set_server_ts(from._internal_server_ts());
  }
  if (from._internal_err() != 0) {
    _this->_internal_set_err(from._internal_err());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ChatSendResponse::CopyFrom(const ChatSendResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.chat.ChatSendResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChatSendResponse::IsInitialized() const {
  return true;
}

void ChatSendResponse::InternalSwap(ChatSendResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ChatSendResponse, _impl_.err_)
      + sizeof(ChatSendResponse::_impl_.err_)
      - PROTOBUF_FIELD_OFFSET(ChatSendResponse, _impl_.msg_id_)>(
          reinterpret_cast<char*>(&_impl_.msg_id_),
          reinterpret_cast<char*>(&other->_impl_.msg_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ChatSendResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chat_2eproto_getter, &descriptor_table_chat_2eproto_once,
      file_level_metadata_chat_2eproto[2]);
}

// ===================================================================

class ChatNotify::_Internal {
 public:
  static const ::protocol::chat::ChatMessage& msg(const ChatNotify* msg);
};

const ::protocol::chat::ChatMessage&
ChatNotify::_Internal::msg(const ChatNotify* msg) {
  return *msg->_impl_.msg_;
}
ChatNotify::ChatNotify(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protocol.chat.ChatNotify)
}
ChatNotify::ChatNotify(const ChatNotify& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ChatNotify* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.msg_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_msg()) {
    _this->_impl_.msg_ = new ::protocol::chat::ChatMessage(*from._impl_.msg_);
  }
  // @@protoc_insertion_point(copy_constructor:protocol.chat.ChatNotify)
}

inline void ChatNotify::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.msg_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ChatNotify::~ChatNotify() {
  // @@protoc_insertion_point(destructor:protocol.chat.ChatNotify)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ChatNotify::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.msg_;
}

void ChatNotify::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ChatNotify::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.chat.ChatNotify)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.msg_ != nullptr) {
    delete _impl_.msg_;
  }
  _impl_.msg_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ChatNotify::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .protocol.chat.ChatMessage msg = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_msg(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ChatNotify::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.chat.ChatNotify)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .protocol.chat.ChatMessage msg = 1;
  if (this->_internal_has_msg()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::msg(this),
        _Internal::msg(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.chat.ChatNotify)
  return target;
}

size_t ChatNotify::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.chat.ChatNotify)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .protocol.chat.ChatMessage msg = 1;
  if (this->_internal_has_msg()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.msg_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ChatNotify::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ChatNotify::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ChatNotify::GetClassData() const { return &_class_data_; }


void ChatNotify::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ChatNotify*>(&to_msg);
  auto& from = static_cast<const ChatNotify&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protocol.chat.ChatNotify)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_msg()) {
    _this->_internal_mutable_msg()->::protocol::chat::ChatMessage::MergeFrom(
        from._internal_msg());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ChatNotify::CopyFrom(const ChatNotify& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.chat.ChatNotify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChatNotify::IsInitialized() const {
  return true;
}

void ChatNotify::InternalSwap(ChatNotify* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.msg_, other->_impl_.msg_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ChatNotify::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chat_2eproto_getter, &descriptor_table_chat_2eproto_once,
      file_level_metadata_chat_2eproto[3]);
}

// ===================================================================

class ChatHistoryRequest::_Internal {
 public:
};

ChatHistoryRequest::ChatHistoryRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protocol.chat.ChatHistoryRequest)
}
ChatHistoryRequest::ChatHistoryRequest(const ChatHistoryRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ChatHistoryRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.after_msg_id_){}
    , decltype(_impl_.target_id_){}
    , decltype(_impl_.limit_){}
    , decltype(_impl_.to_type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.after_msg_id_, &from._impl_.after_msg_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.to_type_) -
    reinterpret_cast<char*>(&_impl_.after_msg_id_)) + sizeof(_impl_.to_type_));
  // @@protoc_insertion_point(copy_constructor:protocol.chat.ChatHistoryRequest)
}

inline void ChatHistoryRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.after_msg_id_){uint64_t{0u}}
    , decltype(_impl_.target_id_){0u}
    , decltype(_impl_.limit_){0u}
    , decltype(_impl_.to_type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ChatHistoryRequest::~ChatHistoryRequest() {
  // @@protoc_insertion_point(destructor:protocol.chat.ChatHistoryRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ChatHistoryRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ChatHistoryRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ChatHistoryRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.chat.ChatHistoryRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.after_msg_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.to_type_) -
      reinterpret_cast<char*>(&_impl_.after_msg_id_)) + sizeof(_impl_.to_type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ChatHistoryRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 target_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.target_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 after_msg_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.after_msg_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 limit = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.limit_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .protocol.chat.TargetType to_type = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_to_type(static_cast<::protocol::chat::TargetType>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ChatHistoryRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.chat.ChatHistoryRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 target_id = 1;
  if (this->_internal_target_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_target_id(), target);
  }

  // uint64 after_msg_id = 2;
  if (this->_internal_after_msg_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_after_msg_id(), target);
  }

  // uint32 limit = 3;
  if (this->_internal_limit() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_limit(), target);
  }

  // .protocol.chat.TargetType to_type = 4;
  if (this->_internal_to_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_to_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.chat.ChatHistoryRequest)
  return target;
}

size_t ChatHistoryRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.chat.ChatHistoryRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 after_msg_id = 2;
  if (this->_internal_after_msg_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_after_msg_id());
  }

  // uint32 target_id = 1;
  if (this->_internal_target_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_target_id());
  }

  // uint32 limit = 3;
  if (this->_internal_limit() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_limit());
  }

  // .protocol.chat.TargetType to_type = 4;
  if (this->_internal_to_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_to_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ChatHistoryRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ChatHistoryRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ChatHistoryRequest::GetClassData() const { return &_class_data_; }


void ChatHistoryRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ChatHistoryRequest*>(&to_msg);
  auto& from = static_cast<const ChatHistoryRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protocol.chat.ChatHistoryRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_after_msg_id() != 0) {
    _this->_internal_set_after_msg_id(from._internal_after_msg_id());
  }
  if (from._internal_target_id() != 0) {
    _this->_internal_set_target_id(from._internal_target_id());
  }
  if (from._internal_limit() != 0) {
    _this->_internal_set_limit(from._internal_limit());
  }
  if (from._internal_to_type() != 0) {
    _this->_internal_set_to_type(from._internal_to_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ChatHistoryRequest::CopyFrom(const ChatHistoryRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.chat.ChatHistoryRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChatHistoryRequest::IsInitialized() const {
  return true;
}

void ChatHistoryRequest::InternalSwap(ChatHistoryRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ChatHistoryRequest, _impl_.to_type_)
      + sizeof(ChatHistoryRequest::_impl_.to_type_)
      - PROTOBUF_FIELD_OFFSET(ChatHistoryRequest, _impl_.after_msg_id_)>(
          reinterpret_cast<char*>(&_impl_.after_msg_id_),
          reinterpret_cast<char*>(&other->_impl_.after_msg_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ChatHistoryRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chat_2eproto_getter, &descriptor_table_chat_2eproto_once,
      file_level_metadata_chat_2eproto[4]);
}

// ===================================================================

class ChatHistoryResponse::_Internal {
 public:
};

ChatHistoryResponse::ChatHistoryResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protocol.chat.ChatHistoryResponse)
}
ChatHistoryResponse::ChatHistoryResponse(const ChatHistoryResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ChatHistoryResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.messages_){from._impl_.messages_}
    , decltype(_impl_.err_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.err_ = from._impl_.err_;
  // @@protoc_insertion_point(copy_constructor:protocol.chat.ChatHistoryResponse)
}

inline void ChatHistoryResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.messages_){arena}
    , decltype(_impl_.err_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ChatHistoryResponse::~ChatHistoryResponse() {
  // @@protoc_insertion_point(destructor:protocol.chat.ChatHistoryResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ChatHistoryResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.messages_.~RepeatedPtrField();
}

void ChatHistoryResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ChatHistoryResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.chat.ChatHistoryResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.messages_.Clear();
  _impl_.err_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ChatHistoryResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .protocol.chat.ChatMessage messages = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_messages(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // .protocol.user.ErrCode err = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_err(static_cast<::protocol::user::ErrCode>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ChatHistoryResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.chat.ChatHistoryResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .protocol.chat.ChatMessage messages = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_messages_size()); i < n; i++) {
    const auto& repfield = this->_internal_messages(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // .protocol.user.ErrCode err = 2;
  if (this->_internal_err() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_err(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.chat.ChatHistoryResponse)
  return target;
}

size_t ChatHistoryResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.chat.ChatHistoryResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .protocol.chat.ChatMessage messages = 1;
  total_size += 1UL * this->_internal_messages_size();
  for (const auto& msg : this->_impl_.messages_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .protocol.user.ErrCode err = 2;
  if (this->_internal_err() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_err());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ChatHistoryResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ChatHistoryResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ChatHistoryResponse::GetClassData() const { return &_class_data_; }


void ChatHistoryResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ChatHistoryResponse*>(&to_msg);
  auto& from = static_cast<const ChatHistoryResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protocol.chat.ChatHistoryResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.messages_.MergeFrom(from._impl_.messages_);
  if (from._internal_err() != 0) {
    _this->_internal_set_err(from._internal_err());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ChatHistoryResponse::CopyFrom(const ChatHistoryResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.chat.ChatHistoryResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChatHistoryResponse::IsInitialized() const {
  return true;
}

void ChatHistoryResponse::InternalSwap(ChatHistoryResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.messages_.InternalSwap(&other->_impl_.messages_);
  swap(_impl_.err_, other->_impl_.err_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ChatHistoryResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chat_2eproto_getter, &descriptor_table_chat_2eproto_once,
      file_level_metadata_chat_2eproto[5]);
}

// ===================================================================

class ChatReadAck::_Internal {
 public:
};

ChatReadAck::ChatReadAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protocol.chat.ChatReadAck)
}
ChatReadAck::ChatReadAck(const ChatReadAck& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ChatReadAck* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.msg_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.msg_id_ = from._impl_.msg_id_;
  // @@protoc_insertion_point(copy_constructor:protocol.chat.ChatReadAck)
}

inline void ChatReadAck::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.msg_id_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ChatReadAck::~ChatReadAck() {
  // @@protoc_insertion_point(destructor:protocol.chat.ChatReadAck)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ChatReadAck::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ChatReadAck::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ChatReadAck::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.chat.ChatReadAck)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msg_id_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ChatReadAck::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 msg_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.msg_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ChatReadAck::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.chat.ChatReadAck)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 msg_id = 1;
  if (this->_internal_msg_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_msg_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.chat.ChatReadAck)
  return target;
}

size_t ChatReadAck::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.chat.ChatReadAck)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 msg_id = 1;
  if (this->_internal_msg_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_msg_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ChatReadAck::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ChatReadAck::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ChatReadAck::GetClassData() const { return &_class_data_; }


void ChatReadAck::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ChatReadAck*>(&to_msg);
  auto& from = static_cast<const ChatReadAck&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protocol.chat.ChatReadAck)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_msg_id() != 0) {
    _this->_internal_set_msg_id(from._internal_msg_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ChatReadAck::CopyFrom(const ChatReadAck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.chat.ChatReadAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChatReadAck::IsInitialized() const {
  return true;
}

void ChatReadAck::InternalSwap(ChatReadAck* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.msg_id_, other->_impl_.msg_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ChatReadAck::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chat_2eproto_getter, &descriptor_table_chat_2eproto_once,
      file_level_metadata_chat_2eproto[6]);
}

// ===================================================================

class ChatPacket::_Internal {
 public:
  static const ::protocol::chat::ChatSendRequest& send_req(const ChatPacket* msg);
  static const ::protocol::chat::ChatSendResponse& send_resp(const ChatPacket* msg);
  static const ::protocol::chat::ChatNotify& notify(const ChatPacket* msg);
  static const ::protocol::chat::ChatHistoryRequest& history_req(const ChatPacket* msg);
  static const ::protocol::chat::ChatHistoryResponse& history_resp(const ChatPacket* msg);
  static const ::protocol::chat::ChatReadAck& read_ack(const ChatPacket* msg);
};

const ::protocol::chat::ChatSendRequest&
ChatPacket::_Internal::send_req(const ChatPacket* msg) {
  return *msg->_impl_.body_.send_req_;
}
const ::protocol::chat::ChatSendResponse&
ChatPacket::_Internal::send_resp(const ChatPacket* msg) {
  return *msg->_impl_.body_.send_resp_;
}
const ::protocol::chat::ChatNotify&
ChatPacket::_Internal::notify(const ChatPacket* msg) {
  return *msg->_impl_.body_.notify_;
}
const ::protocol::chat::ChatHistoryRequest&
ChatPacket::_Internal::history_req(const ChatPacket* msg) {
  return *msg->_impl_.body_.history_req_;
}
const ::protocol::chat::ChatHistoryResponse&
ChatPacket::_Internal::history_resp(const ChatPacket* msg) {
  return *msg->_impl_.body_.history_resp_;
}
const ::protocol::chat::ChatReadAck&
ChatPacket::_Internal::read_ack(const ChatPacket* msg) {
  return *msg->_impl_.body_.read_ack_;
}
void ChatPacket::set_allocated_send_req(::protocol::chat::ChatSendRequest* send_req) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (send_req) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(send_req);
    if (message_arena != submessage_arena) {
      send_req = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, send_req, submessage_arena);
    }
    set_has_send_req();
    _impl_.body_.send_req_ = send_req;
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.chat.ChatPacket.send_req)
}
void ChatPacket::set_allocated_send_resp(::protocol::chat::ChatSendResponse* send_resp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (send_resp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(send_resp);
    if (message_arena != submessage_arena) {
      send_resp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, send_resp, submessage_arena);
    }
    set_has_send_resp();
    _impl_.body_.send_resp_ = send_resp;
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.chat.ChatPacket.send_resp)
}
void ChatPacket::set_allocated_notify(::protocol::chat::ChatNotify* notify) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (notify) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(notify);
    if (message_arena != submessage_arena) {
      notify = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, notify, submessage_arena);
    }
    set_has_notify();
    _impl_.body_.notify_ = notify;
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.chat.ChatPacket.notify)
}
void ChatPacket::set_allocated_history_req(::protocol::chat::ChatHistoryRequest* history_req) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (history_req) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(history_req);
    if (message_arena != submessage_arena) {
      history_req = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, history_req, submessage_arena);
    }
    set_has_history_req();
    _impl_.body_.history_req_ = history_req;
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.chat.ChatPacket.history_req)
}
void ChatPacket::set_allocated_history_resp(::protocol::chat::ChatHistoryResponse* history_resp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (history_resp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(history_resp);
    if (message_arena != submessage_arena) {
      history_resp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, history_resp, submessage_arena);
    }
    set_has_history_resp();
    _impl_.body_.history_resp_ = history_resp;
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.chat.ChatPacket.history_resp)
}
void ChatPacket::set_allocated_read_ack(::protocol::chat::ChatReadAck* read_ack) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (read_ack) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(read_ack);
    if (message_arena != submessage_arena) {
      read_ack = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, read_ack, submessage_arena);
    }
    set_has_read_ack();
    _impl_.body_.read_ack_ = read_ack;
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.chat.ChatPacket.read_ack)
}
ChatPacket::ChatPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protocol.chat.ChatPacket)
}
ChatPacket::ChatPacket(const ChatPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ChatPacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.body_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_body();
  switch (from.body_case()) {
    case kSendReq: {
      _this->_internal_mutable_send_req()->::protocol::chat::ChatSendRequest::MergeFrom(
          from._internal_send_req());
      break;
    }
    case kSendResp: {
      _this->_internal_mutable_send_resp()->::protocol::chat::ChatSendResponse::MergeFrom(
          from._internal_send_resp());
      break;
    }
    case kNotify: {
      _this->_internal_mutable_notify()->::protocol::chat::ChatNotify::MergeFrom(
          from._internal_notify());
      break;
    }
    case kHistoryReq: {
      _this->_internal_mutable_history_req()->::protocol::chat::ChatHistoryRequest::MergeFrom(
          from._internal_history_req());
      break;
    }
    case kHistoryResp: {
      _this->_internal_mutable_history_resp()->::protocol::chat::ChatHistoryResponse::MergeFrom(
          from._internal_history_resp());
      break;
    }
    case kReadAck: {
      _this->_internal_mutable_read_ack()->::protocol::chat::ChatReadAck::MergeFrom(
          from._internal_read_ack());
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:protocol.chat.ChatPacket)
}

inline void ChatPacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.body_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_body();
}

ChatPacket::~ChatPacket() {
  // @@protoc_insertion_point(destructor:protocol.chat.ChatPacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ChatPacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_body()) {
    clear_body();
  }
}

void ChatPacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ChatPacket::clear_body() {
// @@protoc_insertion_point(one_of_clear_start:protocol.chat.ChatPacket)
  switch (body_case()) {
    case kSendReq: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.send_req_;
      }
      break;
    }
    case kSendResp: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.send_resp_;
      }
      break;
    }
    case kNotify: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.notify_;
      }
      break;
    }
    case kHistoryReq: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.history_req_;
      }
      break;
    }
    case kHistoryResp: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.history_resp_;
      }
      break;
    }
    case kReadAck: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.read_ack_;
      }
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = BODY_NOT_SET;
}


void ChatPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.chat.ChatPacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_body();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ChatPacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .protocol.chat.ChatSendRequest send_req = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_send_req(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .protocol.chat.ChatSendResponse send_resp = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_send_resp(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .protocol.chat.ChatNotify notify = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_notify(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .protocol.chat.ChatHistoryRequest history_req = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_history_req(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .protocol.chat.ChatHistoryResponse history_resp = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_history_resp(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .protocol.chat.ChatReadAck read_ack = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_read_ack(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ChatPacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.chat.ChatPacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .protocol.chat.ChatSendRequest send_req = 1;
  if (_internal_has_send_req()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::send_req(this),
        _Internal::send_req(this).GetCachedSize(), target, stream);
  }

  // .protocol.chat.ChatSendResponse send_resp = 2;
  if (_internal_has_send_resp()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::send_resp(this),
        _Internal::send_resp(this).GetCachedSize(), target, stream);
  }

  // .protocol.chat.ChatNotify notify = 3;
  if (_internal_has_notify()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::notify(this),
        _Internal::notify(this).GetCachedSize(), target, stream);
  }

  // .protocol.chat.ChatHistoryRequest history_req = 4;
  if (_internal_has_history_req()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::history_req(this),
        _Internal::history_req(this).GetCachedSize(), target, stream);
  }

  // .protocol.chat.ChatHistoryResponse history_resp = 5;
  if (_internal_has_history_resp()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::history_resp(this),
        _Internal::history_resp(this).GetCachedSize(), target, stream);
  }

  // .protocol.chat.ChatReadAck read_ack = 6;
  if (_internal_has_read_ack()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::read_ack(this),
        _Internal::read_ack(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.chat.ChatPacket)
  return target;
}

size_t ChatPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.chat.ChatPacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (body_case()) {
    // .protocol.chat.ChatSendRequest send_req = 1;
    case kSendReq: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.send_req_);
      break;
    }
    // .protocol.chat.ChatSendResponse send_resp = 2;
    case kSendResp: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.send_resp_);
      break;
    }
    // .protocol.chat.ChatNotify notify = 3;
    case kNotify: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.notify_);
      break;
    }
    // .protocol.chat.ChatHistoryRequest history_req = 4;
    case kHistoryReq: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.history_req_);
      break;
    }
    // .protocol.chat.ChatHistoryResponse history_resp = 5;
    case kHistoryResp: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.history_resp_);
      break;
    }
    // .protocol.chat.ChatReadAck read_ack = 6;
    case kReadAck: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.read_ack_);
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ChatPacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ChatPacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ChatPacket::GetClassData() const { return &_class_data_; }


void ChatPacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ChatPacket*>(&to_msg);
  auto& from = static_cast<const ChatPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protocol.chat.ChatPacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.body_case()) {
    case kSendReq: {
      _this->_internal_mutable_send_req()->::protocol::chat::ChatSendRequest::MergeFrom(
          from._internal_send_req());
      break;
    }
    case kSendResp: {
      _this->_internal_mutable_send_resp()->::protocol::chat::ChatSendResponse::MergeFrom(
          from._internal_send_resp());
      break;
    }
    case kNotify: {
      _this->_internal_mutable_notify()->::protocol::chat::ChatNotify::MergeFrom(
          from._internal_notify());
      break;
    }
    case kHistoryReq: {
      _this->_internal_mutable_history_req()->::protocol::chat::ChatHistoryRequest::MergeFrom(
          from._internal_history_req());
      break;
    }
    case kHistoryResp: {
      _this->_internal_mutable_history_resp()->::protocol::chat::ChatHistoryResponse::MergeFrom(
          from._internal_history_resp());
      break;
    }
    case kReadAck: {
      _this->_internal_mutable_read_ack()->::protocol::chat::ChatReadAck::MergeFrom(
          from._internal_read_ack());
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ChatPacket::CopyFrom(const ChatPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.chat.ChatPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChatPacket::IsInitialized() const {
  return true;
}

void ChatPacket::InternalSwap(ChatPacket* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.body_, other->_impl_.body_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata ChatPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chat_2eproto_getter, &descriptor_table_chat_2eproto_once,
      file_level_metadata_chat_2eproto[7]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace chat
}  // namespace protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protocol::chat::ChatMessage*
Arena::CreateMaybeMessage< ::protocol::chat::ChatMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protocol::chat::ChatMessage >(arena);
}
template<> PROTOBUF_NOINLINE ::protocol::chat::ChatSendRequest*
Arena::CreateMaybeMessage< ::protocol::chat::ChatSendRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protocol::chat::ChatSendRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::protocol::chat::ChatSendResponse*
Arena::CreateMaybeMessage< ::protocol::chat::ChatSendResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protocol::chat::ChatSendResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::protocol::chat::ChatNotify*
Arena::CreateMaybeMessage< ::protocol::chat::ChatNotify >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protocol::chat::ChatNotify >(arena);
}
template<> PROTOBUF_NOINLINE ::protocol::chat::ChatHistoryRequest*
Arena::CreateMaybeMessage< ::protocol::chat::ChatHistoryRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protocol::chat::ChatHistoryRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::protocol::chat::ChatHistoryResponse*
Arena::CreateMaybeMessage< ::protocol::chat::ChatHistoryResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protocol::chat::ChatHistoryResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::protocol::chat::ChatReadAck*
Arena::CreateMaybeMessage< ::protocol::chat::ChatReadAck >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protocol::chat::ChatReadAck >(arena);
}
template<> PROTOBUF_NOINLINE ::protocol::chat::ChatPacket*
Arena::CreateMaybeMessage< ::protocol::chat::ChatPacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protocol::chat::ChatPacket >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
